language: java

before_install:
 - chmod +x gradlew

install:
  - TERM=dumb gradle -q assemble

script:
  - TERM=dumb gradle check --info

jdk:
  - oraclejdk8

env:
  - TERM=dumb


after_success:
- ./gradlew jacocoTestReport coveralls
